FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN pip3 install pip==25.3.0

COPY requirements/requirements.txt .
RUN pip3 install -r requirements.txt

COPY requirements/requirements-test.txt .
RUN pip3 install -r requirements-test.txt

WORKDIR /code

COPY setup.cfg .
COPY pyproject.toml .

COPY src src
COPY tests tests

CMD ["pytest"]
